Doc: Create user-group.md
open-webui/docs pull request #303
Opened 2024-11-26 04:38 UTC by parniantaghipour

I need to refer to my tools and prompt set description.

2024-11-26 05:36 UTC, tjbck commented on docs/features/user-group.md
> +   - Open the Admin Panel and select the **USers** => **Groups** section.
typo

2024-11-26 05:36 UTC, tjbck commented on docs/features/user-group.md
> +# Open WebUI V4: User Group Feature
Unnecessary title

2024-11-26 05:37 UTC, tjbck commented on docs/features/user-group.md
> +The User Group feature introduced in Open WebUI V4 allows users with admin access to define and manage access levels for different groups of users. This feature enhances flexibility by providing the
It's not v4

2024-11-26 05:37 UTC, tjbck commented on docs/features/user-group.md
> +- **Create New Roles**: Introduce custom user levels with specific permissions.
you don't create new roles

2024-11-26 05:39 UTC, tjbck commented on docs/features/user-group.md
> +## Steps to Manage User Groups
Do not describe it, show it using visual aids.

2024-11-26 07:35 UTC, tjbck commented on docs/features/user-group.md
> +Administrators can manage users and groups directly from the **Admin Panel**, which includes two main sections: **Users** and **Groups**.
`User` Page from Admin Panel

2024-11-26 07:35 UTC, tjbck commented on docs/features/user-group.md
> +## Overview
Not needed.

2024-11-26 07:41 UTC, parniantaghipour commented on docs/features/user-group.md
> +   :::tip
Why what?

2024-11-26 07:49 UTC, tjbck commented on docs/features/user-group.md
> +   :::tip
`Admins are unable to grant users direct access to Functions.`

2024-11-26 07:49 UTC, tjbck requested changes

2024-11-26 07:49 UTC, tjbck commented on docs/features/user-group.md
> +### Admin Panel: Groups
Do not close comments that's not resolved.

2024-11-26 07:51 UTC, tjbck commented on docs/features/user-group.md
> +Administrators can manage users and groups directly from the user page from the **Admin Panel**, which includes two main sections: **Users** and **Groups**.
`User`

2024-11-26 07:51 UTC, tjbck commented on docs/features/user-group.md
> +To add new tools, users must have access to **Tools**. The same applies to managing **Knowledge** and **Prompts**.
`have workspace permission`

2024-11-26 08:21 UTC, tjbck commented on docs/features/user-group.md
> +- **Define Access Levels**: Adjust the default permission levels for normal users.
be more explicit here, members with a `user` role.

2024-11-26 08:21 UTC, tjbck commented on docs/features/user-group.md
> +- **Create New User Groups**: Introduce custom user levels with specific permissions.
user levels?

2024-11-26 08:22 UTC, tjbck commented on docs/features/user-group.md
> +To add new tools, users must have **workspace permission** and access to **Tools**. The same applies to managing **Knowledge** and **Prompts**.
explicitly mention this is an example.

2024-11-26 08:22 UTC, tjbck commented on docs/features/user-group.md
> +Users cannot view tools, prompts, or knowledge items added by others. However, admins have full visibility and can access all tools, prompts, and knowledge items, regardless of who added them.
Swap the two sentences and start by saying `Admins ....`

2024-11-26 08:23 UTC, tjbck commented on docs/features/user-group.md
> +#### Users can only view the tools they have added themselves.
do not use `####` for captions

2024-12-09 06:58 UTC, tjbck commented on docs/features/user-group.md
> +![User Tools Permission Demo](/img/tools-user.png)
Unnecessary.

2024-12-09 06:58 UTC, tjbck commented on docs/features/user-group.md
> +## Steps to Manage User Groups
This part hasn't been resolved.

2024-12-09 06:59 UTC, tjbck commented
Feel free to reopen.

2024-12-09 06:59 UTC, closed without merging